name: 'Read Deployment Image Tag'
description: 'Read image tag from deployment configuration file'

inputs:
  env-properties-path:
    description: 'Full path to the env.properties file'
    required: true

outputs:
  tag:
    description: 'The image tag read from the env.properties file'
    value: ${{ steps.read-image-tag.outputs.tag }}

runs:
  using: 'composite'
  steps:
    - name: Read Image Tag from env.properties
      id: read-image-tag
      shell: bash
      run: |
        # Use the provided path to env.properties file
        ENV_PROPERTIES_PATH="${{ inputs.env-properties-path }}"
        
        # Check if env.properties file exists - exit immediately if not found
        if [ ! -f "${ENV_PROPERTIES_PATH}" ]; then
          echo "::error::Required env.properties file not found. Make sure to run the ci pipeline first."
          echo "::error::Deployment cannot proceed without proper configuration"
          exit 1
        fi
        
        echo "Found env.properties file"
        source "${ENV_PROPERTIES_PATH}"
        
        # Verify that IMAGE_TAG is defined in the properties file
        if [ -z "${IMAGE_TAG}" ]; then
          echo "::error::IMAGE_TAG variable not defined in env.properties file"
          echo "::error::Deployment cannot proceed without proper configuration"
          exit 1
        fi
        
        echo "Reading tag from env.properties: ${IMAGE_TAG}"
        echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
