FROM artifactorytest.forge.mastercard.com/docker-hub/eclipse-temurin:17-jdk-ubi9-minimal
COPY ./target/*.jar ./app/app.jar
WORKDIR /app
EXPOSE 8080 8443
USER 1000
ENTRYPOINT ["java", "-jar", "app.jar"]